[project]
name = "ibkr-beancount-compare"
version = "0.1.0"
description = "Compare the IBKR Flex reports to a Ledger/Beancount book"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
